Fix readelf
appPlant/goo pull request #39
Opened 2017-03-16 13:34 UTC by MrBlaTi

fixed db metadata cleaning
fixed db panic
added db test
fixed overlapping use problem when executing a script on one planet multiple times
fixed problem with multiple planets using one tmpfile to use in tableformatter

2017-03-16 14:34 UTC, MrBlaTi commented
fixes #26

2017-03-16 15:44 UTC, katzer requested changes

2017-03-16 15:44 UTC, katzer commented on src/DBHandler.go
> +	tmpDBFile := path.Join(os.Getenv("ORBIT_HOME"), "scripts", tempSQLName)
Verwende besser den TEMP-Ordner des Users oder $ORBIT_HOME/tmp

2017-03-16 15:44 UTC, katzer commented on src/TableFormatter.go
>  	tmpTableFile := path.Join(os.Getenv("ORBIT_HOME"), tmpTableFileName)
Hier ebenso immer einen tmp Ordner verwenden

2017-03-30 14:40 UTC, katzer approved these changes

2017-03-30 14:47 UTC, merged