Ticket 50
appPlant/goo pull request #51
Opened 2017-05-11 10:23 UTC by nbatsukh

closes #50 #49

2017-05-12 07:45 UTC, nbatsukh commented
Before (plain text):
[jobs_output_perlver.txt](https://github.com/appPlant/goo/files/995378/jobs_output_perlver.txt)

Now (JSON Array):

[jobs_output_perlver_json.txt](https://github.com/appPlant/goo/files/995385/jobs_output_perlver_json.txt)

2017-05-12 08:33 UTC, katzer requested changes
Ein Punkt ist mir aufgefallen, der war bereits vorher schon drin. Für jeden Eintrag ist es das Feld _valid_, welches immer auf _false_ steht.

```json
"planets": [
        {
            "id": "p07-int",
            "valid": false,
            "output": "...",
            "errored": false
        }
    ]
```

Wird _valid_ noch verwendet? Wenn nein, kann es raus.

2017-05-12 10:19 UTC, nbatsukh commented
ist raus. tests sind gruen. Kannste dir anschaun.


On 12.05.2017 10:33, Sebastián Katzer wrote:
>
> *@katzer* requested changes on this pull request.
>
> Ein Punkt ist mir aufgefallen, der war bereits vorher schon drin. Für 
> jeden Eintrag ist es das Feld /valid/, welches immer auf /false/ steht.
>
> "planets": [
>          {
>              "id":"p07-int",
>              "valid":false,
>              "output":"...",
>              "errored":false
>          }
>      ]
>
> Wird /valid/ noch verwendet? Wenn nein, kann es raus.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/appPlant/goo/pull/51#pullrequestreview-37781083>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ASlgM7eAGLU9Dx7IlIfE7LSE8hN5ErMPks5r5BlhgaJpZM4NXzNY>.
>

2017-05-14 11:53 UTC, katzer approved these changes

2017-05-14 11:54 UTC, merged